import type { Metadata } from "next";
import Sidebar from "@/components/Sidebar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Danielle Lindblom Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="grid grid-cols-6">
        <Sidebar />
        <main className="col-span-5 bg-gradient-to-br from-violet-950 to-pink-950 to-95% min-h-screen">{children}</main>        
      </body>
    </html>
  );
}
