import type { Metadata } from "next";
import Sidebar from "@/components/Sidebar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Danielle Lindblom Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col overflow-y-scroll h-screen md:grid md:grid-cols-6">
        <Sidebar />
        <main className="md:col-span-5 bg-gradient-to-br from-main-purple from-70% to-main-pink h-screen">{children}</main>        
      </body>
    </html>
  );
}
